---
name: Run VM-MANAGER-BINARIES-PR-MERGE

on:
  pull_request:
    types: [closed]
    branches: 
      - main
      - tmp/ci-testing
    

env:
    EVENT_CONTEXT: ${{ toJSON(github.event) }}
    BUILDTOKEN: test_vmmanager_binaries_merge
    JENKINS_URL: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'tmp/ci-testing'
    runs-on: self-hosted
    steps:
      - name: converting object to json
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "$EVENT_CONTEXT"
      - name: Triggering Jenkins job
        run: |-
                curl --location --request POST  ${{ env.JENKINS_URL }}${{ env.BUILDTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "action": ${{ env.EVENT_CONTEXT }}                      
                        }'
